{{- if .Values.database.enabled }}
{{- if not .Values.database.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app.fullname" . }}-db-secret
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app: db
type: Opaque
data:
  password: {{ .Values.database.postgresql.password | b64enc | quote }}
{{- end }}
{{- end }}